services:
  - type: web
    name: dadcare-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn dadcare.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dadcare.settings.production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
